apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: prediction
spec:
  template:
    spec:
      containers:
      - image: %PREDICTION_IMAGE_URI%
        volumeMounts:
        - mountPath: /opt/app-root/src/.aws/config
          name: config
          subPath: config
        - mountPath: /opt/app-root/src/.aws/credentials
          name: credentials
          subPath: credentials
        env:
        - name: BUCKET_NAME
          value: serverless-workshop-model  # replace with your S3 bucket
        - name: MODEL_FILE_NAME
          value: model.pkl
      volumes:
      - configMap:
          defaultMode: 420
          name: config
        name: config
      - name: credentials
        secret:
          defaultMode: 420
          secretName: credentials
      